# -*- MakeFile -*-

all: multi-threadded_matrix_multi

multi-threadded_matrix_multi: multi-threadded_matrix_multi.c
	gcc multi-threadded_matrix_multi.c -o multi-threadded_matrix_multi -fopenmp

clean:
	rm -fr *.o multi-threadded_matrix_multi *output*